### ISSUE TITLE
Include  alcwithforloop topic description

### ISSUE THREAD

**Issue by chrisoemma** [rafiiramii/ride-my-way#9]
Hi @rafiiramii 

Please add **alcwithforloop** topic in the description area. This will help your mentors to easily find your repo. Link for assistance  https://github.blog/2017-01-31-introducing-topics/

Otherwise nice work

**Comment by rafiiramii** [comment]
i did not understand where to put the topics @chrisoemma

**Comment by rafiiramii** [comment]
i saw it already thanks @chrisoemma
